### ISSUE TITLE
PostgreSQL Passwordless Support

### ISSUE THREAD

**Issue by fangjian0423** [Azure-Samples/acme-fitness-store#103]
Unit 3 use Connector Service for PostgreSQL passwordless connections.

Unit 4 drop PostgreSQL passwordless connections after use KeyVault as secret management.

Unit 7 don't use PostgreSQL passwordless connections in terraform.

I think all of them should use [passwordless connections](https://learn.microsoft.com/en-us/azure/developer/intro/passwordless-overview), it's more security for customers.

**Comment by kelwinpa** [comment]
@fangjian0423 this [PR](https://github.com/Azure-Samples/acme-fitness-store/pull/112) was created

**Comment by selvasingh** [comment]
@kelwinpa and @candicenonsense - close this issue?

**Comment by candicenonsense** [comment]
Closing
