### ISSUE TITLE
In Unit 3, service connector create failed and catalog-service restart failed

### ISSUE THREAD

**Issue by fangjian0423** [Azure-Samples/acme-fitness-store#104]
- create Service Connector for catalog service failed

![image](https://user-images.githubusercontent.com/5254035/209317689-fc8ec888-5b7a-4c15-983b-634ba56243f8.png)

This is a problem in Service Connector and will be fix in Jan.

We could follow this [doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection?toc=%2Fazure%2Fdeveloper%2Fintro%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fintro%2Fbreadcrumb%2Ftoc.json&tabs=sign-in-azure-cli%2Cspring%2Cazure-spring-apps%2Cassign-role-azure-cli#22-create-a-postgresql-non-admin-user-and-grant-permission) to set it manually with Azure hosting service.

- catalog-service restart failed

Now should add a new environment variable: `spring.datasource.azure.passwordless-enabled=true`.

```bash
az spring app update --name ${CATALOG_SERVICE_APP} --env "spring.datasource.azure.passwordless-enabled=true"
```

Service Connector will add this configuration in the future, but now it should be added manually.

**Comment by xfz11** [comment]
@fangjian0423 the above problem is fixed in the latest Service Connector and the new environment variable `spring.datasource.azure.passwordless-enabled=true` is added as well

**Comment by kelwinpa** [comment]
@fangjian0423, @xfz11 since this problem is fixed, should we close this issue?

**Comment by fangjian0423** [comment]
> @fangjian0423, @xfz11 since this problem is fixed, should we close this issue?

Let me close it, thanks @xfz11 for the update.
