### ISSUE TITLE
Mismatch of language and application in the architecture diagram

### ISSUE THREAD

**Issue by saragluna** [Azure-Samples/acme-fitness-store#11]
The [cart application](https://github.com/Azure-Samples/acme-fitness-store/tree/Azure/apps/acme-cart) is a python application and the [order application](https://github.com/Azure-Samples/acme-fitness-store/tree/Azure/apps/acme-order) is a .Net Core one, and it's not correct in the architecture picture.

![](https://github.com/Azure-Samples/acme-fitness-store/raw/Azure/media/architecture.jpg)

**Comment by selvasingh** [comment]
Good one! Thank you @saragluna
