### ISSUE TITLE
Review Spring app for modernization

### ISSUE THREAD

**Issue by JLiuson** [Azure-Samples/acme-fitness-store#111]
Hey @egamma we need to modernize this Spring App and bring it to the cloud for better scale.

Given your extensive Java and JUnit skills 😎 can you please help us on this effort. Please take a look at the tasks below:

- [ ] Review the tests
- [ ] Clean-up the TO DOs
- [ ] Check the security setup

**Comment by dingmeng-xue** [comment]
@egamma , I'm looking into this task. Could you share your insights?
