### ISSUE TITLE
Update provision pipeline to use Terraform only - ensures declarative and can be reconciled against desired state

### ISSUE THREAD

**Issue by selvasingh** [Azure-Samples/acme-fitness-store#116]
Re script in https://github.com/Azure-Samples/acme-fitness-store/blob/Azure/.github/scripts/gateway.sh
The managed Spring Cloud Gateway's desired state can be declaratively expressed and reconciled using Terraform, including route configuration using JSON as a parameter:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_gateway
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_gateway_custom_domain
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_gateway_route_config

Similarly:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_builder
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_build_pack_binding
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_dev_tool_portal
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_application_live_view
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_api_portal

**Comment by candicenonsense** [comment]
@selvasingh we've been working with terraform on bugs on this, will check with my team to see if it's resolved  - @kelwinpa do you know offhand if these are working?

**Comment by kelwinpa** [comment]
All suggestion are already implemented
