### ISSUE TITLE
README.md az spring create, gives error

### ISSUE THREAD

**Issue by chetan-galgali** [Azure-Samples/acme-fitness-store#120]
Command:
az spring create --name ${SPRING_APPS_SERVICE} \
    --resource-group ${RESOURCE_GROUP} \
    --location ${REGION} \
    --sku Enterprise \
    --enable-application-configuration-service \
    --enable-service-registry \
    --enable-gateway \
    --enable-api-portal \
    --enable-alv \
    --enable-app-acc \
    --build-pool-size S2 

This command gives error as
unrecognized arguments:  --enable-alv --enable-app-acc

I even tried with --enable-application-live-view --enable-application-accelerator. But got the same error

**Comment by maly7** [comment]
@chetan-galgali What version of the Azure Spring Apps CLI extension do you have installed?

**Comment by chetan-galgali** [comment]
1.1.5. Below is the complete output:
 az --version
azure-cli                         2.37.0 *

core                              2.37.0 *
telemetry                          1.0.6 *

Extensions:
spring                             1.1.5

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

**Comment by maly7** [comment]
Looks like the CLI instructions in the README need to be updated. Would you please try updating the `spring` extension with `az extension update --name spring`?

**Comment by chetan-galgali** [comment]
@maly7  - I have the latest version. I was able to create the azure-spring-app, without those options.
How do I update an existing service to enable live-view and app-accelerator?

az extension update --name spring
No updates available for 'spring'. Use --debug for more information.

Thank you!

**Comment by maly7** [comment]
You can use these instructions to enable them on an existing service:
* [App Live View](https://learn.microsoft.com/en-us/azure/spring-apps/how-to-use-application-live-view?tabs=Azure-CLI#manage-application-live-view-in-existing-enterprise-tier-instances)
* [App Accelerator](https://learn.microsoft.com/en-us/azure/spring-apps/how-to-use-accelerator?tabs=Azure-CLI#manage-app-accelerator-in-an-existing-enterprise-tier-instance)

**Comment by maly7** [comment]
@chetan-galgali you might still have an issue with the CLI extension version. 

My versions are:

```
azure-cli                         2.47.0

core                              2.47.0
telemetry                          1.0.8

Extensions:
application-insights              0.1.16
spring                            1.10.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0
```

If you run into issues with the other instructions I sent, would you try removing and reinstalling the spring extension?

```bash
az extension remove --name spring
az extension add --name spring
```

**Comment by dingmeng-xue** [comment]
Hi @chetan-galgali , was your issue resolved?
