### ISSUE TITLE
Missing documentation files.

### ISSUE THREAD

**Issue by wkaczurba** [Azure-Samples/acme-fitness-store#140]
Documentation link on the main webpage: https://azure.microsoft.com/en-us/products/spring-apps/ links to missing file https://github.com/Azure-Samples/acme-fitness-store/tree/Azure/workshops/azure-spring-apps-enterprise.

Can it be either reinstantiated, or links corrected? THank you

**Comment by dingmeng-xue** [comment]
@wkaczurba , thanks for reporting. We are fixing it.

**Comment by dingmeng-xue** [comment]
It is resolved.
