### ISSUE TITLE
AI workshop setup instructions are incorrect

### ISSUE THREAD

**Issue by selvasingh** [Azure-Samples/acme-fitness-store#163]
it says cp azure-spring-apps-enterprise/scripts/setup-ai-env-variables-template.sh azure-spring-apps-enterprise/scripts/setup-ai-env-variables.sh

in the fitness repo intermediate workshop, it appears to be creating everything in the project root directory. BTW, many of the values that need to be set in the bash file are not yet available hence, the follow on fails as well.

source ./azure-spring-apps-enterprise/scripts/setup-ai-env-variables.sh

**Comment by anishp55** [comment]
fixed with PR176
