### ISSUE TITLE
OpenAI service creation instructions are incorrect

### ISSUE THREAD

**Issue by selvasingh** [Azure-Samples/acme-fitness-store#164]
<img width="915" alt="image" src="https://github.com/Azure-Samples/acme-fitness-store/assets/3642444/015a39cb-108b-4c5e-9307-7329f91a89f3">

see

<img width="1305" alt="image" src="https://github.com/Azure-Samples/acme-fitness-store/assets/3642444/55e95e18-0f05-4b09-8821-aceb09f27dd1">

**Comment by anishp55** [comment]
```
az cognitiveservices account deployment create -g ${RESOURCE_GROUP} -n ${OPENAI_RESOURCE_NAME} --deployment-name text-embedding-ada-002 --model-name text-embedding-ada-002 --model-version "2" --model-format OpenAI --sku "Standard"  --capacity 120
```

```
az cognitiveservices account deployment create -g ${RESOURCE_GROUP} -n ${OPENAI_RESOURCE_NAME} --deployment-name gpt-35-turbo-16k  --model-name gpt-35-turbo-16k --model-version "0613"   --model-format OpenAI  --sku "Standard" --capacity 120
```

**Comment by selvasingh** [comment]
The first command worked. But the second one is a challenge:

<img width="1465" alt="image" src="https://github.com/Azure-Samples/acme-fitness-store/assets/3642444/76fddf6f-e25f-45e7-b11c-762c0dfe31ab">

@dingmeng-xue

**Comment by LGDoor** [comment]
> The first command worked. But the second one is a challenge:
> 
> <img alt="image" width="1465" src="https://user-images.githubusercontent.com/3642444/268837255-76fddf6f-e25f-45e7-b11c-762c0dfe31ab.png">
> @dingmeng-xue

@selvasingh This is because the quota has only 60 left in this sub. All the AI services share the same quota in a sub.
