### ISSUE TITLE
WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in Azure CLI 2.37.0.

### ISSUE THREAD

**Issue by jialigit** [Azure-Samples/acme-fitness-store#24]
## Context

when exe:
```
az ad app create --display-name ${AD_DISPLAY_NAME} > ad.json
```
then appears:
```
WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in Azure CLI 2.37.0.
```

## Goal
We should solve this warning for better compatibility.

**Comment by maly7** [comment]
Thanks, @jialigit. After reviewing the [changes](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration?tabs=powershell), it appears the only affected command is for adding the redirect uris in `az ad app update`:
> Split --reply-urls into --web-redirect-uris and --public-client-redirect-uris
