### ISSUE TITLE
Issue in Unit-1 while creating an instance of Azure Spring Apps Enterprise

### ISSUE THREAD

**Issue by karthikkc-spektra** [Azure-Samples/acme-fitness-store#50]
In [Unit 1 - Deploy and Build Applications](https://github.com/Azure-Samples/acme-fitness-store#create-azure-spring-apps-service-instance), facing an issue while creating an instance of Azure Spring Apps Enterprise.

After running the given below command, it will create a Azure Spring Apps resource but that is in Failed status:

```
az spring create --name ${SPRING_APPS_SERVICE} \
    --resource-group ${RESOURCE_GROUP} \
    --location ${REGION} \
    --sku Enterprise \
    --enable-application-configuration-service \
    --enable-service-registry \
    --enable-gateway \
    --enable-api-portal \
    --build-pool-size S2 
```

Please find the below screenshots FYR:

![image](https://user-images.githubusercontent.com/83394010/189325936-fb6af6bd-9570-48d3-9d52-9daae8ee2fd8.png)

![image](https://user-images.githubusercontent.com/83394010/189326037-73859630-21ab-4df0-af1f-f8801d534b82.png)

**Comment by murthy-vmware** [comment]
What was the resolution for this error?

**Comment by karthikkc-spektra** [comment]
It was issue with the Subscription.
