### ISSUE TITLE
open command does not work in Azure Cloud Shell/Windows cmd

### ISSUE THREAD

**Issue by xinyiz1226** [Azure-Samples/acme-fitness-store#8]
there are some places in tutorial using commands like "open "https://${GATEWAY_URL}"". It is working in Mac, but does not work in Azure Cloud Shell, Windows cmd, and I guess linux either. It will be good to point it out in the doc.

**Comment by jialigit** [comment]
This error message is trying to tell you that there is no such command called "open". There's nothing wrong with the README.md.

- OSX - open is a universal opener in OSX
- Linux - has xdg-open
- Windows - use start

Refer: https://stackoverflow.com/questions/35811533/git-bash-bash-open-command-not-found

**Comment by selvasingh** [comment]
Let's add a special note for Cloud Shell users, say .. if you are using Cloud Shell, get the Gateway URL and open it in a browser, something like that. And, clearly give instructions for getting the Gateway URL

**Comment by maly7** [comment]
Thanks, @xinyiz1226 and @jialigit. #32 adds instructions for users on azure cloud shell and windows to get the corresponding urls and open them in browsers.
