### ISSUE TITLE
~/.bashrc does not exist in Windows OS

### ISSUE THREAD

**Issue by xinyiz1226** [Azure-Samples/acme-fitness-store#9]
in the readme file, we are talking about set jq alias in bashrc file for Windows:
_Note - The [jq utility](https://stedolan.github.io/jq/download/). On Windows, download [this Windows port of JQ](https://github.com/stedolan/jq/releases) and add the following to the ~/.bashrc file_

But in Windows we need to use set command to do so, as it does not have bashrc file.

**Comment by jialigit** [comment]
I also encounter this. I have to add the exe in the executable path in my env.
